import { StyleSheet } from "react-native";
import { COLORS, RADIUS, SPACING } from "./theme";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  content: {
    paddingTop: SPACING.pageTop,
    paddingHorizontal: SPACING.pageX,
    paddingBottom: 40,
    gap: SPACING.lg,
  },
  headerRow: {
    marginBottom: SPACING.md,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.lg,
  },
  logoBubble: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.brand,
    shadowColor: COLORS.brand,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: COLORS.text,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 13,
    color: COLORS.textMuted,
    marginTop: 2,
    fontWeight: "500",
  },
  searchWrap: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.md,
    minHeight: 52,
    backgroundColor: COLORS.white,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: COLORS.text,
    marginRight: SPACING.xs,
    fontWeight: "500",
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.lightGray,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  iconBtnActive: {
    backgroundColor: COLORS.brand,
  },
  previewWrap: {
    marginTop: SPACING.sm,
    borderRadius: RADIUS.lg,
    overflow: "hidden",
    borderWidth: 0,
    position: "relative",
    backgroundColor: COLORS.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  previewImage: {
    width: "100%",
    height: 180,
  },
  clearPreviewBtn: {
    position: "absolute",
    top: SPACING.md,
    right: SPACING.md,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.pill,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionLabel: {
    marginTop: SPACING.md,
    fontSize: 12,
    letterSpacing: 0.8,
    color: COLORS.textMuted,
    textTransform: "uppercase",
    fontWeight: "700",
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  chip: {
    borderWidth: 1,
    borderColor: COLORS.borderMuted,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.pill,
    paddingHorizontal: SPACING.xl,
    paddingVertical: SPACING.sm,
  },
  chipSelected: {
    backgroundColor: COLORS.brand,
    borderColor: COLORS.brand,
  },
  chipDangerSelected: {
    backgroundColor: COLORS.danger,
    borderColor: COLORS.danger,
  },
  chipText: {
    color: COLORS.chipText,
    fontWeight: "600",
    fontSize: 13,
  },
  chipTextSelected: {
    color: COLORS.white,
  },
  cta: {
    marginTop: SPACING.md,
    minHeight: 54,
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.brand,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
    shadowColor: COLORS.brand,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  ctaText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: -0.3,
  },
  recommendLabel: {
    marginTop: SPACING.lg,
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.text,
    letterSpacing: -0.3,
  },
  shelfLabel: {
    marginTop: SPACING.md,
    marginBottom: SPACING.sm,
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.text,
    letterSpacing: -0.2,
  },
  rowList: {
    paddingVertical: SPACING.xs,
    gap: SPACING.lg,
  },
  card: {
    width: 160,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    overflow: "hidden",
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  cardImage: {
    width: "100%",
    height: 100,
  },
  cardBody: {
    padding: SPACING.md,
    gap: SPACING.xs,
  },
  cardTitle: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: "700",
    minHeight: 32,
    letterSpacing: -0.2,
  },
  cardMeta: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: "500",
  },
});
