export interface Recipe {
  id: string;
  name: string;
  image: string;
  calories: number;
  servings: number;
  cuisineType: string;
  mealType: string;
  healthLabels: string[];
  cautions: string[];
  ingredientLines: string[];
  safety: "safe" | "swap" | "unsafe";
  explanation: string;
  substitutions?: { from: string; to: string }[];
  prepTime?: number; // minutes
  trending?: boolean;
}

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    name: "Grilled Chicken Power Bowl",
    image: "https://images.unsplash.com/photo-1762631383846-6bead15b9796?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxncmlsbGVkJTIwY2hpY2tlbiUyMHByb3RlaW4lMjBib3dsfGVufDF8fHx8MTc3NDkwOTM1MHww&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 520,
    servings: 2,
    cuisineType: "American",
    mealType: "Dinner",
    healthLabels: ["High-Protein", "Gluten-Free"],
    cautions: [],
    ingredientLines: [
      "2 chicken breasts, grilled",
      "1 cup quinoa, cooked",
      "1 avocado, sliced",
      "1 cup cherry tomatoes",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
    ],
    safety: "safe",
    explanation: "High protein and avoids your selected allergens.",
    prepTime: 25,
    trending: true,
  },
  {
    id: "2",
    name: "Salmon & Avocado Plate",
    image: "https://images.unsplash.com/photo-1761315411919-c3bcc6da8224?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYWxtb24lMjBhdm9jYWRvJTIwaGVhbHRoeSUyMGRpbm5lcnxlbnwxfHx8fDE3NzQ5MDkzNTB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 480,
    servings: 2,
    cuisineType: "Mediterranean",
    mealType: "Dinner",
    healthLabels: ["High-Protein", "Dairy-Free"],
    cautions: [],
    ingredientLines: [
      "2 salmon fillets",
      "1 avocado, sliced",
      "1 cup mixed greens",
      "1 lemon, juiced",
      "2 tbsp olive oil",
      "Fresh dill",
    ],
    safety: "safe",
    explanation: "Rich in omega-3 and completely allergen-free for your profile.",
    prepTime: 20,
    trending: true,
  },
  {
    id: "3",
    name: "Quinoa Veggie Salad",
    image: "https://images.unsplash.com/photo-1627483334615-0e070e552a7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxxdWlub2ElMjB2ZWdldGFibGUlMjBzYWxhZCUyMGJvd2x8ZW58MXx8fHwxNzc0OTA5MzUxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 350,
    servings: 3,
    cuisineType: "Asian",
    mealType: "Lunch",
    healthLabels: ["Vegan", "Gluten-Free"],
    cautions: ["Soy"],
    ingredientLines: [
      "1 cup quinoa",
      "1 cup edamame",
      "1 red bell pepper, diced",
      "1 cucumber, diced",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
    ],
    safety: "swap",
    explanation: "Contains soy sauce which can be swapped for a soy-free alternative.",
    substitutions: [{ from: "Soy sauce", to: "Coconut aminos" }],
    prepTime: 15,
  },
  {
    id: "4",
    name: "Turkey Stir-Fry",
    image: "https://images.unsplash.com/photo-1662611284583-f34180194370?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0dXJrZXklMjBzdGlyJTIwZnJ5JTIwdmVnZXRhYmxlc3xlbnwxfHx8fDE3NzQ5MDkzNTF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 410,
    servings: 2,
    cuisineType: "Asian",
    mealType: "Dinner",
    healthLabels: ["High-Protein", "Low-Carb"],
    cautions: ["Dairy", "Nuts"],
    ingredientLines: [
      "500g turkey breast, sliced",
      "2 cups mixed vegetables",
      "2 tbsp butter",
      "1 tbsp peanut oil",
      "Garlic and ginger",
      "Salt and pepper",
    ],
    safety: "unsafe",
    explanation: "Contains dairy (butter) and nuts (peanut oil) which are in your allergen list.",
    prepTime: 30,
  },
  {
    id: "5",
    name: "Lentil & Vegetable Soup",
    image: "https://images.unsplash.com/photo-1635685729867-3dabfb9cd215?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsZW50aWwlMjBzb3VwJTIwaGVhbHRoeSUyMG1lYWx8ZW58MXx8fHwxNzc0OTA5MzUyfDA&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 290,
    servings: 4,
    cuisineType: "Indian",
    mealType: "Dinner",
    healthLabels: ["Vegan", "Gluten-Free", "Low-Calorie"],
    cautions: [],
    ingredientLines: [
      "1.5 cups red lentils",
      "2 carrots, diced",
      "1 onion, diced",
      "2 cloves garlic",
      "1 tsp turmeric",
      "1 tsp cumin",
      "4 cups vegetable broth",
    ],
    safety: "safe",
    explanation: "Low calorie, high fiber, and completely free of your allergens.",
    prepTime: 35,
    trending: true,
  },
  {
    id: "6",
    name: "Avocado Toast & Eggs",
    image: "https://images.unsplash.com/photo-1623691751811-25db777cb59a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhdm9jYWRvJTIwdG9hc3QlMjBicmVha2Zhc3QlMjBoZWFsdGh5fGVufDF8fHx8MTc3NDgwOTkyMHww&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 320,
    servings: 1,
    cuisineType: "American",
    mealType: "Breakfast",
    healthLabels: ["High-Protein", "Dairy-Free"],
    cautions: ["Gluten"],
    ingredientLines: [
      "2 slices sourdough bread",
      "1 ripe avocado",
      "2 poached eggs",
      "Red pepper flakes",
      "Lemon juice",
      "Sea salt",
    ],
    safety: "swap",
    explanation: "Bread contains gluten — swap for gluten-free toast.",
    substitutions: [{ from: "Sourdough bread", to: "Gluten-free bread" }],
    prepTime: 10,
    trending: true,
  },
  {
    id: "7",
    name: "Pasta Primavera",
    image: "https://images.unsplash.com/photo-1761545832779-bc0b4290fc5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXN0YSUyMHRvbWF0byUyMGJhc2lsJTIwaXRhbGlhbnxlbnwxfHx8fDE3NzQ5MDk2Njh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 440,
    servings: 2,
    cuisineType: "Italian",
    mealType: "Lunch",
    healthLabels: ["Vegan"],
    cautions: ["Gluten"],
    ingredientLines: [
      "250g penne pasta",
      "2 cups cherry tomatoes",
      "1 zucchini, sliced",
      "Fresh basil",
      "3 tbsp olive oil",
      "Garlic, minced",
    ],
    safety: "swap",
    explanation: "Pasta contains gluten. Use chickpea pasta for a safe swap.",
    substitutions: [{ from: "Penne pasta", to: "Chickpea penne" }],
    prepTime: 20,
  },
  {
    id: "8",
    name: "Açaí Smoothie Bowl",
    image: "https://images.unsplash.com/photo-1627595146118-ff3ef5129191?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbW9vdGhpZSUyMGJvd2wlMjBhY2FpJTIwZnJ1aXR8ZW53MXx8fHwxNzc0OTA1ODM4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 280,
    servings: 1,
    cuisineType: "Brazilian",
    mealType: "Breakfast",
    healthLabels: ["Vegan", "Gluten-Free", "Low-Calorie"],
    cautions: [],
    ingredientLines: [
      "200g frozen açaí",
      "1 banana",
      "½ cup almond milk",
      "Granola topping",
      "Fresh berries",
      "Coconut flakes",
    ],
    safety: "safe",
    explanation: "Naturally free of all your flagged allergens.",
    prepTime: 5,
    trending: true,
  },
  {
    id: "9",
    name: "Rainbow Buddha Bowl",
    image: "https://images.unsplash.com/photo-1675092789086-4bd2b93ffc69?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidWRkaGElMjBib3dsJTIwY29sb3JmdWwlMjB2ZWdldGFibGVzfGVufDF8fHx8MTc3NDkwOTY2N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 390,
    servings: 2,
    cuisineType: "Fusion",
    mealType: "Lunch",
    healthLabels: ["Vegan", "Gluten-Free", "High-Fiber"],
    cautions: [],
    ingredientLines: [
      "1 cup brown rice",
      "1 cup roasted chickpeas",
      "Shredded purple cabbage",
      "Sliced cucumber & carrots",
      "Tahini dressing",
      "Micro greens",
    ],
    safety: "safe",
    explanation: "Packed with fiber and plant protein — zero allergen overlap.",
    prepTime: 20,
    trending: true,
  },
  {
    id: "10",
    name: "Baja Fish Tacos",
    image: "https://images.unsplash.com/photo-1619301920463-a37f1764eb83?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YWNvcyUyMG1leGljYW4lMjBzdHJlZXQlMjBmb29kfGVufDF8fHx8MTc3NDg2NTk2M3ww&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 360,
    servings: 2,
    cuisineType: "Mexican",
    mealType: "Dinner",
    healthLabels: ["High-Protein"],
    cautions: ["Gluten"],
    ingredientLines: [
      "300g white fish fillets",
      "4 corn tortillas",
      "Shredded cabbage",
      "Lime crema",
      "Fresh cilantro",
      "Pickled jalapeños",
    ],
    safety: "swap",
    explanation: "Use corn tortillas (already included) to keep it gluten-free.",
    substitutions: [{ from: "Flour tortillas", to: "Corn tortillas" }],
    prepTime: 25,
  },
  {
    id: "11",
    name: "Shrimp Pad Thai",
    image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzaHJpbXAlMjBzdGlyJTIwZnJ5JTIwbm9vZGxlcyUyMGFzaWFufGVufDF8fHx8MTc3NDkwOTY2OHww&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 500,
    servings: 2,
    cuisineType: "Thai",
    mealType: "Dinner",
    healthLabels: ["High-Protein"],
    cautions: ["Shellfish", "Nuts"],
    ingredientLines: [
      "200g shrimp, peeled",
      "200g rice noodles",
      "2 eggs",
      "Bean sprouts",
      "Crushed peanuts",
      "Pad Thai sauce",
    ],
    safety: "unsafe",
    explanation: "Contains shellfish (shrimp) and peanuts which are in your allergen list.",
    prepTime: 20,
  },
  {
    id: "12",
    name: "Overnight Oats",
    image: "https://images.unsplash.com/photo-1588346230942-413569272957?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvdmVybmlnaHQlMjBvYXRzJTIwYnJlYWtmYXN0JTIwamFyfGVufDF8fHx8MTc3NDkwOTY2OHww&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 310,
    servings: 1,
    cuisineType: "American",
    mealType: "Breakfast",
    healthLabels: ["Vegan", "High-Fiber"],
    cautions: [],
    ingredientLines: [
      "½ cup rolled oats",
      "1 cup oat milk",
      "2 tbsp chia seeds",
      "1 tbsp maple syrup",
      "Fresh berries",
      "Vanilla extract",
    ],
    safety: "safe",
    explanation: "Dairy-free and nut-free — a perfect allergen-safe breakfast.",
    prepTime: 5,
    trending: true,
  },
  {
    id: "13",
    name: "Chicken Tikka Masala",
    image: "https://images.unsplash.com/photo-1707448829764-9474458021ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwdGlra2ElMjBtYXNhbGElMjBjdXJyeSUyMGluZGlhbnxlbnwxfHx8fDE3NzQ5MDk2Njh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 470,
    servings: 3,
    cuisineType: "Indian",
    mealType: "Dinner",
    healthLabels: ["High-Protein", "Gluten-Free"],
    cautions: ["Dairy"],
    ingredientLines: [
      "600g chicken thighs",
      "1 cup coconut cream",
      "Tikka masala spice blend",
      "Tomato passata",
      "1 onion, diced",
      "Basmati rice to serve",
    ],
    safety: "swap",
    explanation: "Use coconut cream instead of heavy cream for a dairy-free version.",
    substitutions: [{ from: "Heavy cream", to: "Coconut cream" }],
    prepTime: 40,
    trending: true,
  },
  {
    id: "14",
    name: "Greek Salad Bowl",
    image: "https://images.unsplash.com/photo-1769481614068-47cfb4d1f125?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxncmVlayUyMHNhbGFkJTIwbWVkaXRlcnJhbmVhbiUyMGZyZXNofGVufDF8fHx8MTc3NDkwOTY2OXww&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 260,
    servings: 2,
    cuisineType: "Mediterranean",
    mealType: "Lunch",
    healthLabels: ["Low-Calorie", "Gluten-Free", "Keto"],
    cautions: ["Dairy"],
    ingredientLines: [
      "2 cups romaine lettuce",
      "1 cup cucumber, diced",
      "Cherry tomatoes",
      "Kalamata olives",
      "Feta cheese",
      "Olive oil & oregano dressing",
    ],
    safety: "swap",
    explanation: "Feta contains dairy — omit or use dairy-free feta.",
    substitutions: [{ from: "Feta cheese", to: "Dairy-free feta" }],
    prepTime: 10,
  },
  {
    id: "15",
    name: "Protein Pancakes",
    image: "https://images.unsplash.com/photo-1727732003410-9706e9e4c5af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm90ZWluJTIwcGFuY2FrZXMlMjBzdGFjayUyMG1hcGxlJTIwc3lydXB8ZW58MXx8fHwxNzc0OTA5NjY5fDA&ixlib=rb-4.1.0&q=80&w=1080",
    calories: 380,
    servings: 2,
    cuisineType: "American",
    mealType: "Breakfast",
    healthLabels: ["High-Protein"],
    cautions: ["Egg", "Dairy"],
    ingredientLines: [
      "1 cup oat flour",
      "2 scoops vanilla protein powder",
      "2 eggs",
      "½ cup Greek yogurt",
      "1 tsp baking powder",
      "Maple syrup to serve",
    ],
    safety: "unsafe",
    explanation: "Contains eggs and dairy (yogurt) from your allergen list.",
    prepTime: 15,
  },
];

// --- Recommendation shelves ---
export interface RecommendationShelf {
  id: string;
  title: string;
  subtitle: string;
  recipeIds: string[];
}

export const recommendationShelves: RecommendationShelf[] = [
  {
    id: "safe-for-you",
    title: "Safe for You ✅",
    subtitle: "Matches your allergen profile",
    recipeIds: ["1", "2", "5", "8", "9", "12"],
  },
  {
    id: "trending",
    title: "Trending Now 🔥",
    subtitle: "Popular with SafeBite users",
    recipeIds: ["6", "13", "1", "9", "8", "2"],
  },
  {
    id: "quick-easy",
    title: "Quick & Easy ⚡",
    subtitle: "Ready in under 20 minutes",
    recipeIds: ["8", "12", "14", "3", "6", "7"],
  },
  {
    id: "around-world",
    title: "Around the World 🌍",
    subtitle: "Flavors from every cuisine",
    recipeIds: ["13", "10", "7", "5", "11", "14"],
  },
];
